// Generated by gencpp from file n_of_words_pkg/count_wordsResponse.msg
// DO NOT EDIT!


#ifndef N_OF_WORDS_PKG_MESSAGE_COUNT_WORDSRESPONSE_H
#define N_OF_WORDS_PKG_MESSAGE_COUNT_WORDSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace n_of_words_pkg
{
template <class ContainerAllocator>
struct count_wordsResponse_
{
  typedef count_wordsResponse_<ContainerAllocator> Type;

  count_wordsResponse_()
    : count(0)  {
    }
  count_wordsResponse_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct count_wordsResponse_

typedef ::n_of_words_pkg::count_wordsResponse_<std::allocator<void> > count_wordsResponse;

typedef boost::shared_ptr< ::n_of_words_pkg::count_wordsResponse > count_wordsResponsePtr;
typedef boost::shared_ptr< ::n_of_words_pkg::count_wordsResponse const> count_wordsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator1> & lhs, const ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator1> & lhs, const ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace n_of_words_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "602d642babe509c7c59f497c23e716a9";
  }

  static const char* value(const ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x602d642babe509c7ULL;
  static const uint64_t static_value2 = 0xc59f497c23e716a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "n_of_words_pkg/count_wordsResponse";
  }

  static const char* value(const ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int32 count\n"
;
  }

  static const char* value(const ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct count_wordsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::n_of_words_pkg::count_wordsResponse_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // N_OF_WORDS_PKG_MESSAGE_COUNT_WORDSRESPONSE_H
