// Generated by gencpp from file n_of_words_pkg/count_wordsRequest.msg
// DO NOT EDIT!


#ifndef N_OF_WORDS_PKG_MESSAGE_COUNT_WORDSREQUEST_H
#define N_OF_WORDS_PKG_MESSAGE_COUNT_WORDSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace n_of_words_pkg
{
template <class ContainerAllocator>
struct count_wordsRequest_
{
  typedef count_wordsRequest_<ContainerAllocator> Type;

  count_wordsRequest_()
    : words()  {
    }
  count_wordsRequest_(const ContainerAllocator& _alloc)
    : words(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _words_type;
  _words_type words;





  typedef boost::shared_ptr< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct count_wordsRequest_

typedef ::n_of_words_pkg::count_wordsRequest_<std::allocator<void> > count_wordsRequest;

typedef boost::shared_ptr< ::n_of_words_pkg::count_wordsRequest > count_wordsRequestPtr;
typedef boost::shared_ptr< ::n_of_words_pkg::count_wordsRequest const> count_wordsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator1> & lhs, const ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.words == rhs.words;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator1> & lhs, const ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace n_of_words_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f897d3845272d18053a750c1cfb862a";
  }

  static const char* value(const ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f897d3845272d18ULL;
  static const uint64_t static_value2 = 0x053a750c1cfb862aULL;
};

template<class ContainerAllocator>
struct DataType< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "n_of_words_pkg/count_wordsRequest";
  }

  static const char* value(const ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string words\n"
"\n"
;
  }

  static const char* value(const ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.words);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct count_wordsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::n_of_words_pkg::count_wordsRequest_<ContainerAllocator>& v)
  {
    s << indent << "words: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.words);
  }
};

} // namespace message_operations
} // namespace ros

#endif // N_OF_WORDS_PKG_MESSAGE_COUNT_WORDSREQUEST_H
