// Generated by gencpp from file light_robot_pkg/age.msg
// DO NOT EDIT!


#ifndef LIGHT_ROBOT_PKG_MESSAGE_AGE_H
#define LIGHT_ROBOT_PKG_MESSAGE_AGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace light_robot_pkg
{
template <class ContainerAllocator>
struct age_
{
  typedef age_<ContainerAllocator> Type;

  age_()
    : years(0.0)
    , months(0.0)
    , days(0.0)  {
    }
  age_(const ContainerAllocator& _alloc)
    : years(0.0)
    , months(0.0)
    , days(0.0)  {
  (void)_alloc;
    }



   typedef float _years_type;
  _years_type years;

   typedef float _months_type;
  _months_type months;

   typedef float _days_type;
  _days_type days;





  typedef boost::shared_ptr< ::light_robot_pkg::age_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::light_robot_pkg::age_<ContainerAllocator> const> ConstPtr;

}; // struct age_

typedef ::light_robot_pkg::age_<std::allocator<void> > age;

typedef boost::shared_ptr< ::light_robot_pkg::age > agePtr;
typedef boost::shared_ptr< ::light_robot_pkg::age const> ageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::light_robot_pkg::age_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::light_robot_pkg::age_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::light_robot_pkg::age_<ContainerAllocator1> & lhs, const ::light_robot_pkg::age_<ContainerAllocator2> & rhs)
{
  return lhs.years == rhs.years &&
    lhs.months == rhs.months &&
    lhs.days == rhs.days;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::light_robot_pkg::age_<ContainerAllocator1> & lhs, const ::light_robot_pkg::age_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace light_robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::light_robot_pkg::age_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot_pkg::age_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::light_robot_pkg::age_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::light_robot_pkg::age_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot_pkg::age_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot_pkg::age_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::light_robot_pkg::age_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8088e290d061dabc94e1feafd4db363";
  }

  static const char* value(const ::light_robot_pkg::age_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8088e290d061dabULL;
  static const uint64_t static_value2 = 0xc94e1feafd4db363ULL;
};

template<class ContainerAllocator>
struct DataType< ::light_robot_pkg::age_<ContainerAllocator> >
{
  static const char* value()
  {
    return "light_robot_pkg/age";
  }

  static const char* value(const ::light_robot_pkg::age_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::light_robot_pkg::age_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 years\n"
"float32 months\n"
"float32 days\n"
;
  }

  static const char* value(const ::light_robot_pkg::age_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::light_robot_pkg::age_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.years);
      stream.next(m.months);
      stream.next(m.days);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct age_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::light_robot_pkg::age_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::light_robot_pkg::age_<ContainerAllocator>& v)
  {
    s << indent << "years: ";
    Printer<float>::stream(s, indent + "  ", v.years);
    s << indent << "months: ";
    Printer<float>::stream(s, indent + "  ", v.months);
    s << indent << "days: ";
    Printer<float>::stream(s, indent + "  ", v.days);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIGHT_ROBOT_PKG_MESSAGE_AGE_H
