// Generated by gencpp from file light_robot_pkg/light_robot.msg
// DO NOT EDIT!


#ifndef LIGHT_ROBOT_PKG_MESSAGE_LIGHT_ROBOT_H
#define LIGHT_ROBOT_PKG_MESSAGE_LIGHT_ROBOT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace light_robot_pkg
{
template <class ContainerAllocator>
struct light_robot_
{
  typedef light_robot_<ContainerAllocator> Type;

  light_robot_()
    : id(0)
    , name()
    , temperature(0.0)
    , humidity(0.0)  {
    }
  light_robot_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)
    , temperature(0.0)
    , humidity(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _temperature_type;
  _temperature_type temperature;

   typedef float _humidity_type;
  _humidity_type humidity;





  typedef boost::shared_ptr< ::light_robot_pkg::light_robot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::light_robot_pkg::light_robot_<ContainerAllocator> const> ConstPtr;

}; // struct light_robot_

typedef ::light_robot_pkg::light_robot_<std::allocator<void> > light_robot;

typedef boost::shared_ptr< ::light_robot_pkg::light_robot > light_robotPtr;
typedef boost::shared_ptr< ::light_robot_pkg::light_robot const> light_robotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::light_robot_pkg::light_robot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::light_robot_pkg::light_robot_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::light_robot_pkg::light_robot_<ContainerAllocator1> & lhs, const ::light_robot_pkg::light_robot_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.name == rhs.name &&
    lhs.temperature == rhs.temperature &&
    lhs.humidity == rhs.humidity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::light_robot_pkg::light_robot_<ContainerAllocator1> & lhs, const ::light_robot_pkg::light_robot_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace light_robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::light_robot_pkg::light_robot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot_pkg::light_robot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::light_robot_pkg::light_robot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::light_robot_pkg::light_robot_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot_pkg::light_robot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot_pkg::light_robot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::light_robot_pkg::light_robot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16767b4b63fd3551b69c6c06672a0bf6";
  }

  static const char* value(const ::light_robot_pkg::light_robot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16767b4b63fd3551ULL;
  static const uint64_t static_value2 = 0xb69c6c06672a0bf6ULL;
};

template<class ContainerAllocator>
struct DataType< ::light_robot_pkg::light_robot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "light_robot_pkg/light_robot";
  }

  static const char* value(const ::light_robot_pkg::light_robot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::light_robot_pkg::light_robot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"string name\n"
"float32 temperature\n"
"float32 humidity\n"
;
  }

  static const char* value(const ::light_robot_pkg::light_robot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::light_robot_pkg::light_robot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.temperature);
      stream.next(m.humidity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct light_robot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::light_robot_pkg::light_robot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::light_robot_pkg::light_robot_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
    s << indent << "humidity: ";
    Printer<float>::stream(s, indent + "  ", v.humidity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIGHT_ROBOT_PKG_MESSAGE_LIGHT_ROBOT_H
