// Generated by gencpp from file n_words_pkg/count_words.msg
// DO NOT EDIT!


#ifndef N_WORDS_PKG_MESSAGE_COUNT_WORDS_H
#define N_WORDS_PKG_MESSAGE_COUNT_WORDS_H

#include <ros/service_traits.h>


#include <n_words_pkg/count_wordsRequest.h>
#include <n_words_pkg/count_wordsResponse.h>


namespace n_words_pkg
{

struct count_words
{

typedef count_wordsRequest Request;
typedef count_wordsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct count_words
} // namespace n_words_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n_words_pkg::count_words > {
  static const char* value()
  {
    return "4dd4fc0aa84b04c0886a72138fb27c19";
  }

  static const char* value(const ::n_words_pkg::count_words&) { return value(); }
};

template<>
struct DataType< ::n_words_pkg::count_words > {
  static const char* value()
  {
    return "n_words_pkg/count_words";
  }

  static const char* value(const ::n_words_pkg::count_words&) { return value(); }
};


// service_traits::MD5Sum< ::n_words_pkg::count_wordsRequest> should match
// service_traits::MD5Sum< ::n_words_pkg::count_words >
template<>
struct MD5Sum< ::n_words_pkg::count_wordsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n_words_pkg::count_words >::value();
  }
  static const char* value(const ::n_words_pkg::count_wordsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n_words_pkg::count_wordsRequest> should match
// service_traits::DataType< ::n_words_pkg::count_words >
template<>
struct DataType< ::n_words_pkg::count_wordsRequest>
{
  static const char* value()
  {
    return DataType< ::n_words_pkg::count_words >::value();
  }
  static const char* value(const ::n_words_pkg::count_wordsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n_words_pkg::count_wordsResponse> should match
// service_traits::MD5Sum< ::n_words_pkg::count_words >
template<>
struct MD5Sum< ::n_words_pkg::count_wordsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n_words_pkg::count_words >::value();
  }
  static const char* value(const ::n_words_pkg::count_wordsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n_words_pkg::count_wordsResponse> should match
// service_traits::DataType< ::n_words_pkg::count_words >
template<>
struct DataType< ::n_words_pkg::count_wordsResponse>
{
  static const char* value()
  {
    return DataType< ::n_words_pkg::count_words >::value();
  }
  static const char* value(const ::n_words_pkg::count_wordsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N_WORDS_PKG_MESSAGE_COUNT_WORDS_H
