// Generated by gencpp from file adding_pkg/addingRequest.msg
// DO NOT EDIT!


#ifndef ADDING_PKG_MESSAGE_ADDINGREQUEST_H
#define ADDING_PKG_MESSAGE_ADDINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace adding_pkg
{
template <class ContainerAllocator>
struct addingRequest_
{
  typedef addingRequest_<ContainerAllocator> Type;

  addingRequest_()
    : x(0)
    , y(0)  {
    }
  addingRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::adding_pkg::addingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::adding_pkg::addingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct addingRequest_

typedef ::adding_pkg::addingRequest_<std::allocator<void> > addingRequest;

typedef boost::shared_ptr< ::adding_pkg::addingRequest > addingRequestPtr;
typedef boost::shared_ptr< ::adding_pkg::addingRequest const> addingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::adding_pkg::addingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::adding_pkg::addingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::adding_pkg::addingRequest_<ContainerAllocator1> & lhs, const ::adding_pkg::addingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::adding_pkg::addingRequest_<ContainerAllocator1> & lhs, const ::adding_pkg::addingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace adding_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::adding_pkg::addingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::adding_pkg::addingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::adding_pkg::addingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::adding_pkg::addingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adding_pkg::addingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adding_pkg::addingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::adding_pkg::addingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b834ede922a0fff22c43585c533b49f";
  }

  static const char* value(const ::adding_pkg::addingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b834ede922a0fffULL;
  static const uint64_t static_value2 = 0x22c43585c533b49fULL;
};

template<class ContainerAllocator>
struct DataType< ::adding_pkg::addingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adding_pkg/addingRequest";
  }

  static const char* value(const ::adding_pkg::addingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::adding_pkg::addingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n"
"int64 y\n"
"\n"
;
  }

  static const char* value(const ::adding_pkg::addingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::adding_pkg::addingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::adding_pkg::addingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::adding_pkg::addingRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADDING_PKG_MESSAGE_ADDINGREQUEST_H
