// Generated by gencpp from file adding_pkg/addingResponse.msg
// DO NOT EDIT!


#ifndef ADDING_PKG_MESSAGE_ADDINGRESPONSE_H
#define ADDING_PKG_MESSAGE_ADDINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace adding_pkg
{
template <class ContainerAllocator>
struct addingResponse_
{
  typedef addingResponse_<ContainerAllocator> Type;

  addingResponse_()
    : sum(0)  {
    }
  addingResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::adding_pkg::addingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::adding_pkg::addingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct addingResponse_

typedef ::adding_pkg::addingResponse_<std::allocator<void> > addingResponse;

typedef boost::shared_ptr< ::adding_pkg::addingResponse > addingResponsePtr;
typedef boost::shared_ptr< ::adding_pkg::addingResponse const> addingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::adding_pkg::addingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::adding_pkg::addingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::adding_pkg::addingResponse_<ContainerAllocator1> & lhs, const ::adding_pkg::addingResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::adding_pkg::addingResponse_<ContainerAllocator1> & lhs, const ::adding_pkg::addingResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace adding_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::adding_pkg::addingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::adding_pkg::addingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::adding_pkg::addingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::adding_pkg::addingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adding_pkg::addingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adding_pkg::addingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::adding_pkg::addingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::adding_pkg::addingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::adding_pkg::addingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adding_pkg/addingResponse";
  }

  static const char* value(const ::adding_pkg::addingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::adding_pkg::addingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 sum\n"
"\n"
;
  }

  static const char* value(const ::adding_pkg::addingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::adding_pkg::addingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::adding_pkg::addingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::adding_pkg::addingResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADDING_PKG_MESSAGE_ADDINGRESPONSE_H
