// Generated by gencpp from file adding_pkg/adding.msg
// DO NOT EDIT!


#ifndef ADDING_PKG_MESSAGE_ADDING_H
#define ADDING_PKG_MESSAGE_ADDING_H

#include <ros/service_traits.h>


#include <adding_pkg/addingRequest.h>
#include <adding_pkg/addingResponse.h>


namespace adding_pkg
{

struct adding
{

typedef addingRequest Request;
typedef addingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct adding
} // namespace adding_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::adding_pkg::adding > {
  static const char* value()
  {
    return "875493d2ec8f0bdc18c62960322c94b7";
  }

  static const char* value(const ::adding_pkg::adding&) { return value(); }
};

template<>
struct DataType< ::adding_pkg::adding > {
  static const char* value()
  {
    return "adding_pkg/adding";
  }

  static const char* value(const ::adding_pkg::adding&) { return value(); }
};


// service_traits::MD5Sum< ::adding_pkg::addingRequest> should match
// service_traits::MD5Sum< ::adding_pkg::adding >
template<>
struct MD5Sum< ::adding_pkg::addingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::adding_pkg::adding >::value();
  }
  static const char* value(const ::adding_pkg::addingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::adding_pkg::addingRequest> should match
// service_traits::DataType< ::adding_pkg::adding >
template<>
struct DataType< ::adding_pkg::addingRequest>
{
  static const char* value()
  {
    return DataType< ::adding_pkg::adding >::value();
  }
  static const char* value(const ::adding_pkg::addingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::adding_pkg::addingResponse> should match
// service_traits::MD5Sum< ::adding_pkg::adding >
template<>
struct MD5Sum< ::adding_pkg::addingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::adding_pkg::adding >::value();
  }
  static const char* value(const ::adding_pkg::addingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::adding_pkg::addingResponse> should match
// service_traits::DataType< ::adding_pkg::adding >
template<>
struct DataType< ::adding_pkg::addingResponse>
{
  static const char* value()
  {
    return DataType< ::adding_pkg::adding >::value();
  }
  static const char* value(const ::adding_pkg::addingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ADDING_PKG_MESSAGE_ADDING_H
