// Generated by gencpp from file count_pkg/cmplx.msg
// DO NOT EDIT!


#ifndef COUNT_PKG_MESSAGE_CMPLX_H
#define COUNT_PKG_MESSAGE_CMPLX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace count_pkg
{
template <class ContainerAllocator>
struct cmplx_
{
  typedef cmplx_<ContainerAllocator> Type;

  cmplx_()
    : real(0.0)
    , imaginary(0.0)  {
    }
  cmplx_(const ContainerAllocator& _alloc)
    : real(0.0)
    , imaginary(0.0)  {
  (void)_alloc;
    }



   typedef double _real_type;
  _real_type real;

   typedef double _imaginary_type;
  _imaginary_type imaginary;





  typedef boost::shared_ptr< ::count_pkg::cmplx_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::count_pkg::cmplx_<ContainerAllocator> const> ConstPtr;

}; // struct cmplx_

typedef ::count_pkg::cmplx_<std::allocator<void> > cmplx;

typedef boost::shared_ptr< ::count_pkg::cmplx > cmplxPtr;
typedef boost::shared_ptr< ::count_pkg::cmplx const> cmplxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::count_pkg::cmplx_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::count_pkg::cmplx_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::count_pkg::cmplx_<ContainerAllocator1> & lhs, const ::count_pkg::cmplx_<ContainerAllocator2> & rhs)
{
  return lhs.real == rhs.real &&
    lhs.imaginary == rhs.imaginary;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::count_pkg::cmplx_<ContainerAllocator1> & lhs, const ::count_pkg::cmplx_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace count_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::count_pkg::cmplx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::count_pkg::cmplx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::count_pkg::cmplx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::count_pkg::cmplx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::count_pkg::cmplx_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::count_pkg::cmplx_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::count_pkg::cmplx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f79948d85872c3174fd7b3b73c94ede5";
  }

  static const char* value(const ::count_pkg::cmplx_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf79948d85872c317ULL;
  static const uint64_t static_value2 = 0x4fd7b3b73c94ede5ULL;
};

template<class ContainerAllocator>
struct DataType< ::count_pkg::cmplx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "count_pkg/cmplx";
  }

  static const char* value(const ::count_pkg::cmplx_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::count_pkg::cmplx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 real\n"
"float64 imaginary\n"
;
  }

  static const char* value(const ::count_pkg::cmplx_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::count_pkg::cmplx_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.real);
      stream.next(m.imaginary);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmplx_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::count_pkg::cmplx_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::count_pkg::cmplx_<ContainerAllocator>& v)
  {
    s << indent << "real: ";
    Printer<double>::stream(s, indent + "  ", v.real);
    s << indent << "imaginary: ";
    Printer<double>::stream(s, indent + "  ", v.imaginary);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COUNT_PKG_MESSAGE_CMPLX_H
